package com.meizu.savior;

import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

public class Constants {
    public static final String ADD_ANNOTATION = "Add";
    public static final String ARRAY_TYPE = "[";
    public static final String ASPECTJ_AROUND_CLASS = "org.aspectj.runtime.internal.AroundClosure";
    public static Class AddAnnotationClass = null;
    public static final String BOOLEAN = "boolean";
    public static final String BYTE = "byte";
    public static final String CHAR = "char";
    public static final String CLASSES_DEX_NAME = "classes.dex";
    public static final String CONSTRUCTOR = "Constructor";
    public static final String DEFAULT_MAPPING_FILE = "/savior/mapping.txt";
    public static final String DOUBLE = "double";
    public static final String FLOAT = "float";
    public static final String GET_REAL_PARAMETER = "getRealParameter";
    public static final int HTTP_NO_DATA = 19002;
    public static final String INLINE_PATCH_SUFFIX = "InLinePatch";
    public static final String INSERT_FIELD_NAME = "changeQuickRedirect";
    public static final String INT = "int";
    public static final String INTERFACE_NAME = "com.meizu.savior.ChangeQuickRedirect";
    public static final Integer JOB_SCHEDULER_ID = 10010;
    public static final String KEY_CODE = "code";
    public static final String KEY_LINK = "link";
    public static final String KEY_MD5 = "md5";
    public static final String KEY_PATCH_VER_CODE = "patchVersion";
    public static final String KEY_VALUE = "value";
    public static final String LAMBDA_MODIFY = "SaviorModify";
    public static final String LANG_BOOLEAN = "java.lang.Boolean";
    public static final String LANG_BYTE = "java.lang.Byte";
    public static final String LANG_CHARACTER = "Character";
    public static final String LANG_DOUBLE = "java.lang.Double";
    public static final String LANG_FLOAT = "java.lang.Float";
    public static final String LANG_INT = "java.lang.Integer";
    public static final String LANG_LONG = "java.lang.Long";
    public static final String LANG_SHORT = "java.lang.Short";
    public static final String LANG_VOID = "java.lang.Void";
    public static final String[] LIB_NAME_ARRAY = {"baksmali-2.2.5.jar", "smali-2.2.5.jar", "d2j-tools/d2j-jar2dex.sh"};
    public static final String LONG = "long";
    public static final String METHOD_MAP_OUT_PATH = "/outputs/savior/methodsMap.savior";
    public static final String METHOD_MAP_PATH = "/savior/methodsMap.savior";
    public static final String MODIFY_ANNOTATION = "Modify";
    public static Class ModifyAnnotationClass = null;
    public static final List<String> NO_NEED_REFLECT_CLASS = Arrays.asList(new String[]{"android.os.Bundle", "android.os.BaseBundle"});
    public static final char OBJECT_TYPE = 'L';
    public static final Boolean OBSCURE = true;
    public static final String ORIGINCLASS = "originClass";
    public static final String PACKNAME_END = ";";
    public static final String PACKNAME_START = String.valueOf(OBJECT_TYPE);
    public static final String PARAM_APK_VERSION_NAME = "vn";
    public static final String PARAM_FLYME_VERSION = "fv";
    public static final String PARAM_MODEL = "model";
    public static final String PARAM_PATCH_DOWNLOAD_DATE = "patchDownloadDate";
    public static final String PARAM_PATCH_VERSION_CODE = "patchVersion";
    public static final String PARAM_PKG_NAME = "pkgName";
    public static final String PARAM_PKG_VERSION = "pkgVersion";
    public static final String PARAM_SIGN = "sign";
    public static final String PATACH_DEX_NAME = "patch.dex";
    public static final String PATACH_JAR_NAME = "patch.jar";
    public static final String PATCH_CONTROL_SUFFIX = "Control";
    public static final String PATCH_EXECUTE = "patch execute ,other extension will be ignore ";
    public static final String PATCH_PACKAGENAME = "com.meizu.savior.patch";
    public static final String PATCH_QUERY_URL = "http://api.photos.meizu.com/patch/link.do";
    public static final String PATCH_SUFFIX = "Patch";
    public static final String PATCH_TEMPLATE_FULL_NAME = "com.meizu.savior.utils.PatchTemplate";
    public static final String PRIMITIVE_TYPE = "ZCBSIJFDV";
    public static final Set RFileClassSet = new HashSet();
    public static final String SAVIOR_APK_HASH_FILE_NAME = "savior.apkhash";
    public static final String SAVIOR_ASSIST_SUFFIX = "SaviorAssist";
    public static final String SAVIOR_GENERATE_DIRECTORY = "outputs/savior";
    public static final String SAVIOR_PUBLIC_SUFFIX = "SaviorPublic";
    public static final String SAVIOR_UTILS_FULL_NAME = "com.meizu.savior.utils.EnhancedSaviorUtils";
    public static final String SAVIOR_XML = "savior.xml";
    public static final String SHORT = "short";
    public static final String SMALI_INVOKE_SUPER_COMMAND = "invoke-super";
    public static final String SMALI_INVOKE_VIRTUAL_COMMAND = "invoke-virtual";
    public static final String STATICFLAG = "staticSavior";
    public static final String TEMP_SH_DIRECTORY = "temp_sh";
    public static final String VOID = "void";
    public static final String ZIP_FILE_NAME = "meizu.jar";
    public static boolean isLogging = true;

    static {
        RFileClassSet.add("R$array");
        RFileClassSet.add("R$xml");
        RFileClassSet.add("R$styleable");
        RFileClassSet.add("R$style");
        RFileClassSet.add("R$string");
        RFileClassSet.add("R$raw");
        RFileClassSet.add("R$menu");
        RFileClassSet.add("R$layout");
        RFileClassSet.add("R$integer");
        RFileClassSet.add("R$id");
        RFileClassSet.add("R$drawable");
        RFileClassSet.add("R$dimen");
        RFileClassSet.add("R$color");
        RFileClassSet.add("R$bool");
        RFileClassSet.add("R$attr");
        RFileClassSet.add("R$anim");
    }
}
